@ECHO OFF
SETLOCAL

SET CYGWINHOME=%~dp0
SET CYGWINROOT="%~dp0cygwin"

:SLAPOS_WRAPPER
CMD.EXE /C %CYGWINROOT%\bin\bash --login %*
SET RETVALUE=%ERRORLEVEL%
GOTO END

:END
ENDLOCAL 
EXIT %RETVALUE%
