#!/bin/sh
set -e

. /usr/share/debconf/confmodule

if [ -f /etc/openvpn/vifib.conf ]; then
    cp -f /etc/openvpn/vifib.conf /etc/openvpn/vifib.backup.conf
    mkdir -p /etc/openvpn/vifib-keys
    cp -rf /etc/openvpn/vifib-keys /etc/openvpn/vifib-backup-keys
    sed -i "s/\/etc\/openvpn\/vifib-keys/\/etc\/openvpn\/vifib-backup-keys/g"  /etc/openvpn/vifib.backup.conf
fi

#DEBHELPER#

exit 0
